### ISSUE TITLE
Imagen de PostgreSQL

### ISSUE THREAD

**Issue by urkonn** [mxabierto/dockerfile#2]

**Comment by bcessa** [comment]
@urkonn alguna versión en especifico?

**Comment by urkonn** [comment]
9.4

**Comment by bcessa** [comment]
la ultima version estable parece ser la 9.4.4; vi que hay una imagen oficial y creo podemos usar esa para no mantener otra :grin: 

https://github.com/docker-library/postgres/blob/cd294bf8dfdf4a74b2077aa6413fa579f9bf07de/9.4/Dockerfile

**Comment by rodowi** [comment]
:+1: oficial
